### ISSUE TITLE
医药的数据集不公开？

### ISSUE THREAD

**Issue by abc668** [AtmaHou/Task-Oriented-Dialogue-Dataset-Survey#10]
![image](https://user-images.githubusercontent.com/44453385/54652067-6e05ef80-4af0-11e9-9c81-2371af64b197.png)
医药的数据集不公开？如图
第二个医药的数据集，来自复旦的，打开链接后发现是不公开的，需要账号才能进网站，楼主有没有获取到他们的数据集呢？怎么获取？求指教，谢谢啦。

**Comment by AtmaHou** [comment]
emmm， 不太清楚欸，直接发邮件问论文作者吧~~~

**Comment by abc668** [comment]
您有备份吗？有的话可以发我一份？

**Comment by AtmaHou** [comment]
抱歉啊，我没用过这个数据集

**Comment by abc668** [comment]
没关系：）
