### ISSUE TITLE
multi-domain 的意思不一致

### ISSUE THREAD

**Issue by luweishuang** [AtmaHou/Task-Oriented-Dialogue-Dataset-Survey#12]
我发现 虽然这个项目里公开的数据集 不止一个都宣称是 多域，但是 它们的概念不太一样的。像 MultiWOZ 2.0 ，它是在一个完整对话中可能涉及到多个主题。而 Stanford Dialog Dataset 里，它的 multi-domain 体现在整个数据集里的对话涉及到多个主题，但是在任一个完整对话中，它是单主题的，对吗？

**Comment by AtmaHou** [comment]
是的，你对两个语境下multi-domain的理解都是对的~
