### ISSUE TITLE
The link of dstc2-clean.zip is unavailable. Can you help fix it?

### ISSUE THREAD

**Issue by taolusi** [AtmaHou/Task-Oriented-Dialogue-Dataset-Survey#13]

**Comment by AtmaHou** [comment]
Sure. Do you have the new link of it?

**Comment by taolusi** [comment]
> 
> 
> Sure. Do you have the new link of it?

I do not have the new link. Can you provide it to me?

**Comment by taolusi** [comment]
> 
> 
> Sure. Do you have the new link of it?

I do not have the new link. Can you provide it to me? Thank you.

**Comment by AtmaHou** [comment]
I think the data owner has closed the access to download, check the following link:
http://mi.eng.cam.ac.uk/~nm480/dstc2-clean.zip

**Comment by taolusi** [comment]
The link is unavailable, any other way to get the data?

**Comment by AtmaHou** [comment]
> The link is unavailable, any other way to get the data?

I know it is unavailable, but the owner's contact is included in the 403 page. 
Maybe you can contact the owner directly and contribute a new link if you succeed.

**Comment by taolusi** [comment]
OK. Thank you.

**Comment by p4rk3r** [comment]
Hi... I did not check in detail... but it seems the authors contacted the dataset owner (NBT paper) to get it... Worth to have a look? -> https://github.com/Divye02/baby-jarvis/commit/2e3b65aef6d62ce9a4595b88c573350f38bda2a9

**Comment by AtmaHou** [comment]
OK, thanks for the information~
I'll consider adding them as a tip in next update.
