### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by hulumei123** [AtmaHou/Task-Oriented-Dialogue-Dataset-Survey#21]
请问有中文的任务型对话数据集吗？

**Comment by AtmaHou** [comment]
SMP 2018 还是2019 有一个评测，那个有中文的数据集，是公开的，可以试试~

**Comment by hulumei123** [comment]
请问有多轮对话的中文数据集吗？我刚刚看了一下，SMP是单轮数据集，类似于英文的ATIS




| |
谭志鹏
邮箱：18717753697@163.com
|

签名由 网易邮箱大师 定制

在2020年03月08日 15:35，Atma 写道：

SMP 2018 还是2019 有一个评测，那个有中文的数据集，是公开的，可以试试~

**Comment by AtmaHou** [comment]
多轮的有 Minglie 老师他们最近新发布的数据~ 
CrossWOZ: A Large-Scale Chinese Cross-Domain Task-Oriented Dialogue Dataset
